[package]
name = "mercury"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
reqwest = { version = "0.12.12", features = ["blocking"] }
tao = "0.31.1"
tray-icon = { path="crates/tray-icon" }
