[package]
name = "planet"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
reqwest = { version="0.12.12", features=["blocking"] }
tokio = { version="1.42.0", features=["macros", "rt-multi-thread"] }
tray-icon = "0.19.2"