[package]
name = "mercury"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
reqwest = "0.12.12"
tokio = { version="1.42.0", features=["macros", "rt-multi-thread"] }
tray-icon = "0.19.2"
